set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# BCD Input values
set_property PACKAGE_PIN V17 [get_ports {bcd_value[0][0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[0][0]}]
set_property PACKAGE_PIN V16 [get_ports {bcd_value[0][1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[0][1]}]
set_property PACKAGE_PIN W16 [get_ports {bcd_value[0][2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[0][2]}]
set_property PACKAGE_PIN W17 [get_ports {bcd_value[0][3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[0][3]}]
set_property PACKAGE_PIN W15 [get_ports {bcd_value[1][0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[1][0]}]
set_property PACKAGE_PIN V15 [get_ports {bcd_value[1][1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[1][1]}]
set_property PACKAGE_PIN W14 [get_ports {bcd_value[1][2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[1][2]}]
set_property PACKAGE_PIN W13 [get_ports {bcd_value[1][3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {bcd_value[1][3]}]
	
#Binary output values
set_property PACKAGE_PIN U16 [get_ports {binary_value[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[0]}]
set_property PACKAGE_PIN E19 [get_ports {binary_value[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[1]}]
set_property PACKAGE_PIN U19 [get_ports {binary_value[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[2]}]
set_property PACKAGE_PIN V19 [get_ports {binary_value[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[3]}]
set_property PACKAGE_PIN W18 [get_ports {binary_value[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[4]}]
set_property PACKAGE_PIN U15 [get_ports {binary_value[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[5]}]
set_property PACKAGE_PIN U14 [get_ports {binary_value[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[6]}]
set_property PACKAGE_PIN V14 [get_ports {binary_value[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_value[7]}]
	
#Ready and done 
set_property PACKAGE_PIN V13 [get_ports done_tick]					
	set_property IOSTANDARD LVCMOS33 [get_ports done_tick]
set_property PACKAGE_PIN V3 [get_ports ready]					
	set_property IOSTANDARD LVCMOS33 [get_ports ready]
	
#Reset and load
set_property PACKAGE_PIN V2 [get_ports reset]					
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T3 [get_ports load]					
	set_property IOSTANDARD LVCMOS33 [get_ports load]
